### PR TITLE
Hapi v17

### LINKED ISSUE #2: Hapi v17 Support
### Overview
If you are not aware yet, Hapi v17 is making the transition from callbacks to `async`/`await`, as well as deprecating some other rarely used functionality. This is a breaking change that may make your plugin no longer compatible with the Hapi API.

#### Changelog
Draft release notes can be found here: https://github.com/hapijs/hapi/issues/3658

#### Target Release
The target release date for v17 is the beginning of *November*.

### Tasks
- [ ] Reply to this to acknowledge that you are actively maintaining this module and are willing to update it
- [ ] Update plugin to be fully `async`/`await` compatible using the `v17` branch from Hapi for testing
  #### Possible dev flow for updating
  - Clone Hapi
  - `npm link` within the Hapi repo
  - `npm link hapi` within your plugin repo
  - Your plugin will now be using `v17` of Hapi branch for tests
- [ ] Release new major version of your plugin on `npm`. Please use a major version increment as this will be a breaking change and it would be terrible for it to sneak into current versions of Hapi.

### Notes
* Support is being dropped for all versions of Node `<8.0.0`. 
* Hapi `v16` will continue to be supported for as long as there exists a Node LTS actively being supported that is not compatible with `v17`.
* Targeted release date is November 1st, 2017. Please try to have your plugin updated before then.
* This issue is being opened because your plugin is listed on the official hapi website

### PR DESCRIPTION
**Pull request by henrikruscon**
Fully fixes/closes #2 

Updates everything to work with Hapi v17 and Sinon 3 ✌️ 

Full coverage tests passed.

### CODE REVIEW

**Comment by henrikruscon** [comment]
Any review or merge? ✌️

**Comment by marcuspoehls** [comment]
I think it's better to use a named export `plugin` instead of `default`. This is what hapi supports natively, so you could `await server.register(require('hapi-graceful-pm2'))` instead of `await server.reigster(require('hapi-graceful-pm2').default)`

@henrikdahl What do you think?

**Comment by patrickdundas** [comment]
Any possibility of this being merged soon? This is a breaking change!

**Comment by sadafie** [comment]
@roylines review and merge please? looks like at least a few of us need this. Thanks!

**Comment by marcuspoehls** [comment]
Here's a hapi v17 compatible plugin:
https://github.com/fs-opensource/hapi-pulse

Hope this helps everyone to keep their zero downtime deployments 😊

**Comment by roylines** [comment]
Apologies on the delay to merging this. All done now.

**Comment by patrickdundas** [comment]
Thank you! Keep up the good work

**Pull request merged**
